=== x0r3k/XML_Parsing/src/main/resources/AutoShop.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema
	xmlns="http://www.w3.org/2001/XMLSchema"
 	targetNamespace="http://autoshop.com/details"
 	xmlns:tns="http://autoshop.com/details"
 >
	<element name="DetailsList">
        <complexType>
			<sequence>
				<element name="Detail" type="tns:Detail" maxOccurs="unbounded" />
			</sequence>
		</complexType>
    </element>
    
    <element name="CarsList">
    	<complexType>
    		<sequence>
    			<element name="Car" type="tns:Car" maxOccurs="unbounded" />
    		</sequence>
    	</complexType>
    </element>
	
	<element name="OrdersList">
		<complexType>
			<sequence>
				<element name="Order" type="tns:Order" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	
	<complexType name="Detail">
		<complexContent>
			<extension base="tns:Entity_ID">
				<sequence>
					<element name="Title" type="tns:ShortString"/>
					<element name="Price" type="tns:Decimal8_2" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	
	<complexType name="Car">
		<complexContent>
			<extension base="tns:Entity_ID">
				<sequence>
					<element name="Brand" type="tns:ShortString"/>
					<element name="Model" type="tns:ShortString"/>
					<element name="Year" type="tns:Year"/>
					<element name="Engine" type="tns:Engine"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	
	<complexType name="Engine">
		<choice>
			<sequence>
				<element name="Cylinder" type="tns:NonNegativeNumber"/>
				<element name="Capacity" type="tns:Decimal6_1"/>
			</sequence>
			<sequence>
				<element name="Power" type="tns:Decimal6_1"/>
			</sequence>
		</choice>
	</complexType>
	
	<complexType name="Order">
		<complexContent>
			<extension base="tns:Entity_ID">
				<sequence>
					<element name="OrderInfo" type="tns:OrderInfo"/>
					<element name="UserInfo" type="tns:UserInfo"/>
					<element name="ShoppingCart" type="tns:ShoppingCart"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	
	<complexType name="OrderInfo">
		<sequence>
			<element name="Date" type="tns:DateTime"/>
			<element name="Status" type="tns:OrderStatus"/>
			<element name="TotalPrice" type="tns:Decimal8_2"/>
		</sequence>
	</complexType>
	
	<complexType name="UserInfo">
		<sequence>
			<element name="Name" type="tns:ShortString"/>
			<element name="Gender" type="tns:Gender"/>
			<element name="Email" type="tns:Email"/>
			<element name="BirthDate" type="tns:Date"/>
			<element name="City" type="tns:ShortString"/>
		</sequence>
	</complexType>
	
	<complexType name="ShoppingCart">
		<sequence>
			<element name="ShoppingCartItem" type="tns:ShoppingCartItem" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<complexType name="ShoppingCartItem">
		<complexContent>
		<extension base="tns:Entity_ID">
			<sequence>
				<element name="Title" type="tns:ShortString"/>
				<element name="Price" type="tns:Decimal8_2"/>
				<element name="Count" type="tns:NonNegativeNumber"/>
			</sequence>
		</extension>
		</complexContent>
	</complexType>

	
	<simpleType name="Year">
		<restriction base="integer">
	       	<maxInclusive value="2020"/>
	       	<minInclusive value="1920"/>
	     </restriction>
   	</simpleType>
	
	<simpleType name="Email">
		<restriction base="string">
	       	<pattern value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})"/>
	     </restriction>
   	</simpleType>
   	
   	<simpleType name="Gender">
		<restriction base="string">
			<enumeration value="M" />
			<enumeration value="F" />
		</restriction>
	</simpleType>
	
	<simpleType name="OrderStatus">
		<restriction base="string">
			<enumeration value="Completed" />
			<enumeration value="Opened" />
			<enumeration value="Payed" />
			<enumeration value="Canceled" />
			<enumeration value="Returned" />
			<enumeration value="Waiting for payment" />
		</restriction>
	</simpleType>
	
	<simpleType name="Date">
		<restriction base="date">
			<minInclusive value="1900-01-01"/>
		</restriction>
	</simpleType>
	
	<simpleType name="DateTime">
		<restriction base="dateTime">
			<minInclusive value="1900-01-01T00:00:00"/>
		</restriction>
	</simpleType>
	
	<simpleType name="ShortString">
		<restriction base="string">
			<minLength value="1"/>
			<maxLength value="45"/>
		</restriction>
	</simpleType>
	
	<simpleType name="LongString">
		<restriction base="string">
			<minLength value="1"/>
			<maxLength value="200"/>
		</restriction>
	</simpleType>
	
	<simpleType name="Decimal8_2">
		<restriction base="decimal">
			<fractionDigits value="2"/>
			<totalDigits value="8"/>
			<minExclusive value="0.99"/>
			<maxExclusive value="123456.99"/>
		</restriction>
	</simpleType>
	
	<simpleType name="Decimal6_1">
		<restriction base="decimal">
			<fractionDigits value="1"/>
			<totalDigits value="6"/>
			<minExclusive value="0.0"/>
			<maxExclusive value="12345.9"/>
		</restriction>
	</simpleType>
	
	<simpleType name="NonNegativeNumber">
		<restriction base="integer">
			<minInclusive value="0"/>
		</restriction>
	</simpleType>
	
	<complexType name="Entity_ID" abstract="true">
		<attribute name="id" type="tns:NonNegativeNumber" use="required" />
	</complexType>
</schema>

=== x0r3k/XML_Parsing/src/main/resources/Orders.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:OrdersList
	xmlns:tns="http://autoshop.com/details"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://autoshop.com/details AutoShop.xsd"
>

	<Order id='1'>
		<OrderInfo>
			<Date>2020-09-25T09:12:22</Date>
			<Status>Canceled</Status>
			<TotalPrice>309.57</TotalPrice>
		</OrderInfo>
		<UserInfo>
			<Name>Kirill</Name>
			<Gender>M</Gender>
			<Email>test@mail.com</Email>
			<BirthDate>1917-08-27</BirthDate>
			<City>Kharkiv</City>
		</UserInfo>
		<ShoppingCart>
			<ShoppingCartItem id="1">
				<Title>Brake pads</Title>
				<Price>29.99</Price>
				<Count>2</Count>
			</ShoppingCartItem>
			<ShoppingCartItem id="2">
				<Title>Oxygen Sensor</Title>
				<Price>249.59</Price>
				<Count>1</Count>
			</ShoppingCartItem>
		</ShoppingCart>
	</Order>
	
 	<Order id='2'>
		<OrderInfo>
			<Date>2020-08-21T23:12:32</Date>
			<Status>Completed</Status>
			<TotalPrice>3761.95</TotalPrice>
		</OrderInfo>
		<UserInfo>
			<Name>Marina</Name>
			<Gender>F</Gender>
			<Email>mail123@mail.com</Email>
			<BirthDate>2000-03-16</BirthDate>
			<City>Kyiv</City>
		</UserInfo>
		<ShoppingCart>
			<ShoppingCartItem id="1">
				<Title>Automatic Transmission</Title>
				<Price>3609.99</Price>
				<Count>1</Count>
			</ShoppingCartItem>
			<ShoppingCartItem id="2">
				<Title>Door Handle</Title>
				<Price>37.99</Price>
				<Count>4</Count>
			</ShoppingCartItem>
		</ShoppingCart>
	</Order>
</tns:OrdersList>

=== x0r3k/XML_Parsing/src/main/resources/AutoShop.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:OrdersList
	xmlns:tns="http://autoshop.com/details"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://autoshop.com/details AutoShop.xsd"
>
  <Order id="0">
    <OrderInfo>
      <Date>2001-12-31T12:00:00</Date>
      <Status>Completed</Status>
      <TotalPrice>31.98</TotalPrice>
    </OrderInfo>
    <UserInfo>
      <Name>Name</Name>
      <Gender>M</Gender>
      <Email>email@mail.com</Email>
      <BirthDate>2001-01-01</BirthDate>
      <City>City</City>
    </UserInfo>
    <ShoppingCart>
      <ShoppingCartItem id="1">
        <Title>Title</Title>
        <Price>15.99</Price>
        <Count>2</Count>
      </ShoppingCartItem>
    </ShoppingCart>
  </Order>
</tns:OrdersList>

=== x0r3k/XML_Parsing/src/main/resources/Cars.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:CarsList
	xmlns:tns="http://autoshop.com/details"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://autoshop.com/details AutoShop.xsd"
>
 	<Car id='1'>
 		<Brand>Mazda</Brand>
 		<Model>CX-7</Model>
 		<Year>2012</Year>
 		<Engine>
 			<Cylinder>4</Cylinder>
 			<Capacity>2.5</Capacity>
 		</Engine>
 	</Car>
 	<Car id='2'>
 		<Brand>Toyota</Brand>
 		<Model>Camry</Model>
 		<Year>2015</Year>
 		<Engine>
 			<Cylinder>6</Cylinder>
 			<Capacity>3.5</Capacity>
 		</Engine>
 	</Car>
 	<Car id='3'>
 		<Brand>Tesla</Brand>
 		<Model>X</Model>
 		<Year>2017</Year>
 		<Engine>
 			<Power>250</Power>
 		</Engine>
 	</Car>
</tns:CarsList>

=== x0r3k/XML_Parsing/src/main/resources/DetailsList.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:DetailsList
	xmlns:tns="http://autoshop.com/details"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://autoshop.com/details AutoShop.xsd"
>
 	<Detail id='1'>
 		<Title>Brake Pads</Title>
 		<Price>1129.99</Price>
 	</Detail>
 	<Detail id='2'>
 		<Title>Battery</Title>
 		<Price>199.99</Price>
 	</Detail>
 	<Detail id='3'>
 		<Title>Gasoline Fuel Pump</Title>
 		<Price>26.99</Price>
 	</Detail>
</tns:DetailsList>
